### PR TITLE
country picker bug resolved, package/class refracted, firebase user n…

### LINKED ISSUE #48: Phone number UI problem
Problem in UI in Verify Phone number Activity 

Country code and phoneNumberField stack together

### PR DESCRIPTION
**Pull request by adityasonel**
Changes done,

-  package structure refracted. classes moved to it's respective package for example authentication related classes moved to auth package.
- country code ui bug fixed in Phone1VerificationActivity that is now refracted to GetPhoneNumberActivity
- firebase-auth-user null check added on home-activity. now if user is not logged in get-started-activity will be visible else home-activity

### CODE REVIEW

**Review by aayu24 — CHANGES_REQUESTED** [review]
There is an issue with HomeActivity.java - Firebase.getUserInstance, that causes users to skip verification and directly reach home page.

**Comment by kenchoong** [comment]
Just checked the HomeActivity.java, what I seen is work as expected.

1. First launch the app 
2. Didn't login,so I redirect to OnboardActivity 
3. Clicked "Skip" in on OnboardActivity,redirected to GetPhoneNumberActivity 

Tested on Oppo F5

**Review by kenchoong — APPROVED** [review]
Just checked the HomeActivity.java, what I seen is work as expected.

1. First launch the app
2. Didn't login,so I redirect to OnboardActivity
3. Clicked "Skip" in on OnboardActivity,redirected to GetPhoneNumberActivity

Tested on Oppo F5

**Comment by prasadpilla** [comment]
@adityasonel Can you please extract the functional fixes of of this and create another PR? with the module changes it has become impossible to resolve the merge conflicts on top of the app name changes

**Pull request closed without merging**
