### PR TITLE
Issue 83/72

### LINKED ISSUE #72: "Get started" screen UI alignment issue
Device Nexus 6P Simulator

image

### PR DESCRIPTION
**Pull request by adityasonel**

### CODE REVIEW

**Comment by kenchoong** [comment]
Tested

Screenshot_2020-04-07-16-04-50-10

**Review by aayu24 — DISMISSED** [review]
The UI fixes are working.

**Comment by kenchoong** [comment]
Screenshot_2020-04-07-16-04-50-10


Tested but didnt see the text view "PRACTICE SOCIAL DISTANCING"

**Review by kenchoong — CHANGES_REQUESTED** [review]
Screenshot_2020-04-07-16-04-50-10

Tested but didnt see the "Practice social distancing" text

**Comment by kenchoong** [comment]
Tested,now look like this 

Just changed the height and margin of `onboarding_item`,not a good solution,but still work so far

Screenshot_2020-04-07-17-06-37-31

**Review by aayu24 — APPROVED** [review]
All the UI elements are fine now.

**Pull request merged**
